<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Lua.Bytecode\Lua.Bytecode.csproj" />
        <ProjectReference Include="..\Lua.Runtime\Lua.Runtime.csproj" />
        <ProjectReference Include="..\Lua.Syntax\Lua.Syntax.csproj" />
    </ItemGroup>

</Project>
