namespace Lua.Bytecode.Instructions;

public static class LuaOpcodeTables
{
    private static readonly OpcodeDescriptor[] Opcodes =
    [
        new("MOVE", LuaInstructionFormat.IABC),
        new("LOADI", LuaInstructionFormat.IAsBx),
        new("LOADF", LuaInstructionFormat.IAsBx),
        new("LOADK", LuaInstructionFormat.IABx),
        new("LOADKX", LuaInstructionFormat.IABx),
        new("LOADFALSE", LuaInstructionFormat.IABC),
        new("LFALSESKIP", LuaInstructionFormat.IABC),
        new("LOADTRUE", LuaInstructionFormat.IABC),
        new("LOADNIL", LuaInstructionFormat.IABC),
        new("GETUPVAL", LuaInstructionFormat.IABC),
        new("SETUPVAL", LuaInstructionFormat.IABC),
        new("GETTABUP", LuaInstructionFormat.IABC),
        new("GETTABLE", LuaInstructionFormat.IABC),
        new("GETI", LuaInstructionFormat.IABC),
        new("GETFIELD", LuaInstructionFormat.IABC),
        new("SETTABUP", LuaInstructionFormat.IABC),
        new("SETTABLE", LuaInstructionFormat.IABC),
        new("SETI", LuaInstructionFormat.IABC),
        new("SETFIELD", LuaInstructionFormat.IABC),
        new("NEWTABLE", LuaInstructionFormat.IvABC),
        new("SELF", LuaInstructionFormat.IABC),
        new("ADDI", LuaInstructionFormat.IABC),
        new("ADDK", LuaInstructionFormat.IABC),
        new("SUBK", LuaInstructionFormat.IABC),
        new("MULK", LuaInstructionFormat.IABC),
        new("MODK", LuaInstructionFormat.IABC),
        new("POWK", LuaInstructionFormat.IABC),
        new("DIVK", LuaInstructionFormat.IABC),
        new("IDIVK", LuaInstructionFormat.IABC),
        new("BANDK", LuaInstructionFormat.IABC),
        new("BORK", LuaInstructionFormat.IABC),
        new("BXORK", LuaInstructionFormat.IABC),
        new("SHLI", LuaInstructionFormat.IABC),
        new("SHRI", LuaInstructionFormat.IABC),
        new("ADD", LuaInstructionFormat.IABC),
        new("SUB", LuaInstructionFormat.IABC),
        new("MUL", LuaInstructionFormat.IABC),
        new("MOD", LuaInstructionFormat.IABC),
        new("POW", LuaInstructionFormat.IABC),
        new("DIV", LuaInstructionFormat.IABC),
        new("IDIV", LuaInstructionFormat.IABC),
        new("BAND", LuaInstructionFormat.IABC),
        new("BOR", LuaInstructionFormat.IABC),
        new("BXOR", LuaInstructionFormat.IABC),
        new("SHL", LuaInstructionFormat.IABC),
        new("SHR", LuaInstructionFormat.IABC),
        new("MMBIN", LuaInstructionFormat.IABC),
        new("MMBINI", LuaInstructionFormat.IABC),
        new("MMBINK", LuaInstructionFormat.IABC),
        new("UNM", LuaInstructionFormat.IABC),
        new("BNOT", LuaInstructionFormat.IABC),
        new("NOT", LuaInstructionFormat.IABC),
        new("LEN", LuaInstructionFormat.IABC),
        new("CONCAT", LuaInstructionFormat.IABC),
        new("CLOSE", LuaInstructionFormat.IABC),
        new("TBC", LuaInstructionFormat.IABC),
        new("JMP", LuaInstructionFormat.IsJ),
        new("EQ", LuaInstructionFormat.IABC),
        new("LT", LuaInstructionFormat.IABC),
        new("LE", LuaInstructionFormat.IABC),
        new("EQK", LuaInstructionFormat.IABC),
        new("EQI", LuaInstructionFormat.IABC),
        new("LTI", LuaInstructionFormat.IABC),
        new("LEI", LuaInstructionFormat.IABC),
        new("GTI", LuaInstructionFormat.IABC),
        new("GEI", LuaInstructionFormat.IABC),
        new("TEST", LuaInstructionFormat.IABC),
        new("TESTSET", LuaInstructionFormat.IABC),
        new("CALL", LuaInstructionFormat.IABC),
        new("TAILCALL", LuaInstructionFormat.IABC),
        new("RETURN", LuaInstructionFormat.IABC),
        new("RETURN0", LuaInstructionFormat.IABC),
        new("RETURN1", LuaInstructionFormat.IABC),
        new("FORLOOP", LuaInstructionFormat.IABx),
        new("FORPREP", LuaInstructionFormat.IABx),
        new("TFORPREP", LuaInstructionFormat.IABx),
        new("TFORCALL", LuaInstructionFormat.IABC),
        new("TFORLOOP", LuaInstructionFormat.IABx),
        new("SETLIST", LuaInstructionFormat.IvABC),
        new("CLOSURE", LuaInstructionFormat.IABx),
        new("VARARG", LuaInstructionFormat.IABC),
        new("GETVARG", LuaInstructionFormat.IABC),
        new("ERRNNIL", LuaInstructionFormat.IABx),
        new("VARARGPREP", LuaInstructionFormat.IABC),
        new("EXTRAARG", LuaInstructionFormat.IAx)
    ];

    public static int Count => Opcodes.Length;

    public static string GetName(LuaOpcode opcode) => Opcodes[(int)opcode].Name;

    public static LuaInstructionFormat GetFormat(LuaOpcode opcode) => Opcodes[(int)opcode].Format;

    private readonly record struct OpcodeDescriptor(string Name, LuaInstructionFormat Format);
}
